<?php
    $outbound = $data['outbound'];
    $return = $data['return'];
?>
<div class="container">
    <div class="panel-group">

        <div class="panel panel-primary">
            <div class="panel-heading"> Your flight</div>
            <div class="panel-body">
                    <div class="row"><div class="col-xs-12"><i class="fa fa-plane fa-lg"></i> Outbound flight</div>

                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12">
                            <?php echo $outbound['title_date']; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-5 text-center"><?php echo $outbound['origin']; ?></div>
                        <div class="col-xs-2 text-center"><i class="fa fa-arrow-right" aria-hidden="true"></i></div>
                        <div class="col-xs-5 text-center"><?php echo $outbound['destiny']; ?></div>
                    </div>
                    <div class="row">
                        <div class="col-xs-5 text-center"><?php echo $outbound['time']; ?></div>
                        <div class="col-xs-2 text-center"><i class="fa fa-arrow-right" aria-hidden="true"></i></div>
                        <div class="col-xs-5 text-center"><?php echo $outbound['time']; ?></div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-xs-offset-10"><span class="text-right">€ <?php echo $outbound['price']; ?> price per person</span></div>
                    </div>

                    <?php if($data['is_return']): ?>
                        <div class="row"><div class="col-xs-12"><i class="fa fa-plane fa-lg fa-rotate-270"></i> Return flight</div>

                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-xs-12">
                                <?php echo $return['title_date']; ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-5 text-center"><?php echo $return['origin']; ?></div>
                            <div class="col-xs-2 text-center"><i class="fa fa-arrow-right" aria-hidden="true"></i></div>
                            <div class="col-xs-5 text-center"><?php echo $return['destiny']; ?></div>
                        </div>
                        <div class="row">
                            <div class="col-xs-5 text-center"><?php echo $this->escapeHTML($return['time']); ?></div>
                            <div class="col-xs-2 text-center"><i class="fa fa-arrow-right" aria-hidden="true"></i></div>
                            <div class="col-xs-5 text-center"><?php echo $this->escapeHTML($return['time']); ?></div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-xs-offset-10"><span class="text-right">€ <?php echo $return['price']; ?> price per person</span></div>
                        </div>
                    <?php endif; ?>
                        <hr>
                        <div class="row"><div class="col-xs-12"><i class="fa fa-plane fa-group"></i> Passenger(s)</div>
                         <hr>
                         <?php if($data['adults']>0): ?>
                            <div class="row">
                                <div class="col-xs-12 col-xs-offset-1">
                                    <?php echo $data['adults']; ?> Adult(s)
                                </div>
                            </div>
                         <?php endif; ?>
                         <?php if($data['children']>0): ?>
                        <div class="row">
                            <div class="col-xs-12 col-xs-offset-1">
                                <?php echo $data['children']; ?> Children
                            </div>
                        </div>
                         <?php endif; ?>
                        <?php if($data['infant']>0): ?>
                            <div class="row">
                                <div class="col-xs-12 col-xs-offset-1">
                                    <?php echo $data['infant']; ?> Infant
                                </div>
                            </div>
                        <?php endif; ?>
                         <hr>
                            <div class="row">
                                <div class="col-xs-2 text-center">
                                    <span><b>Total Price</b></span>
                                </div>
                                <div class="col-xs-8">
                                </div>
                                <div class="col-xs-2 price">
                                    <h4>€ <?php echo $this->escapeHTML($data['total_price']); ?></h4>
                                </div>
                            </div>
                    </div>
            </div>
        </div>

    </div>
</div>